/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2017
 */

var Configuration = {
    //The base Uri for API calls
    BASEURI : "http://recog.calltrackingmetrics.com/v1"

};

module.exports = Configuration;
