
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of CreateARepresentativeRequest
 *
 * @constructor
 */
CreateARepresentativeRequest = function (obj) {
    if(!obj) {
        this.name = null;     
        this.gender = null;     
    } else {
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
        this.gender = (obj.gender !== undefined && obj.gender !== null)? obj.gender : null;
    }
};

CreateARepresentativeRequest.prototype = new BaseModel();
CreateARepresentativeRequest.prototype.constructor = CreateARepresentativeRequest;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CreateARepresentativeRequest.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
CreateARepresentativeRequest.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CreateARepresentativeRequest.prototype.getGender = function() {
    return this.gender;
};

/**
 * Setter for Gender
 * 
 * @param {string} value 
 */
CreateARepresentativeRequest.prototype.setGender = function(value) {
    this.gender = value;
};


module.exports = CreateARepresentativeRequest;
