
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of GetAPIVersionAndTestAuthenticationResponse
 *
 * @constructor
 */
GetAPIVersionAndTestAuthenticationResponse = function (obj) {
    if(!obj) {
        this.version = null;     
        this.root = null;     
        this.description = null;     
    } else {
        this.version = (obj.version !== undefined && obj.version !== null)? obj.version : null;
        this.root = (obj.root !== undefined && obj.root !== null)? obj.root : null;
        this.description = (obj.description !== undefined && obj.description !== null)? obj.description : null;
    }
};

GetAPIVersionAndTestAuthenticationResponse.prototype = new BaseModel();
GetAPIVersionAndTestAuthenticationResponse.prototype.constructor = GetAPIVersionAndTestAuthenticationResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetAPIVersionAndTestAuthenticationResponse.prototype.getVersion = function() {
    return this.version;
};

/**
 * Setter for Version
 * 
 * @param {string} value 
 */
GetAPIVersionAndTestAuthenticationResponse.prototype.setVersion = function(value) {
    this.version = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetAPIVersionAndTestAuthenticationResponse.prototype.getRoot = function() {
    return this.root;
};

/**
 * Setter for Root
 * 
 * @param {string} value 
 */
GetAPIVersionAndTestAuthenticationResponse.prototype.setRoot = function(value) {
    this.root = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetAPIVersionAndTestAuthenticationResponse.prototype.getDescription = function() {
    return this.description;
};

/**
 * Setter for Description
 * 
 * @param {string} value 
 */
GetAPIVersionAndTestAuthenticationResponse.prototype.setDescription = function(value) {
    this.description = value;
};


module.exports = GetAPIVersionAndTestAuthenticationResponse;
