
/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of UpdateAClientResponse
 *
 * @constructor
 */
UpdateAClientResponse = function (obj) {
    if(!obj) {
        this.id = null;     
        this.name = null;     
        this.createdAt = null;     
        this.gender = null;     
        this.links = null;     
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
    } else {
        this.id = (obj.id !== undefined && obj.id !== null)? obj.id : null;
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
        this.createdAt = (obj.created_at !== undefined && obj.created_at !== null)? obj.created_at : null;
        this.gender = (obj.gender !== undefined && obj.gender !== null)? obj.gender : null;
        this.links = (obj.links !== undefined && obj.links !== null)? obj.links : null;
        //Append to variable dictionary
        this._variableDict['createdAt'] = 'created_at';
    }
};

UpdateAClientResponse.prototype = new BaseModel();
UpdateAClientResponse.prototype.constructor = UpdateAClientResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
UpdateAClientResponse.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
UpdateAClientResponse.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
UpdateAClientResponse.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
UpdateAClientResponse.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
UpdateAClientResponse.prototype.getCreatedAt = function() {
    return this.createdAt;
};

/**
 * Setter for CreatedAt
 * 
 * @param {string} value 
 */
UpdateAClientResponse.prototype.setCreatedAt = function(value) {
    this.createdAt = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
UpdateAClientResponse.prototype.getGender = function() {
    return this.gender;
};

/**
 * Setter for Gender
 * 
 * @param {string} value 
 */
UpdateAClientResponse.prototype.setGender = function(value) {
    this.gender = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
UpdateAClientResponse.prototype.getLinks = function() {
    return this.links;
};

/**
 * Setter for Links
 * 
 * @param {array} value 
 */
UpdateAClientResponse.prototype.setLinks = function(value) {
    this.links = value;
};


module.exports = UpdateAClientResponse;
