/**
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/04/2017
 */

var _request = require('../Http/Client/RequestClient');
var _configuration = require('../configuration');
var _APIHelper = require('../APIHelper');

var AuthorizationController = {

    /**
     * The API root is namespaced behind the version number as in http://recog.calltrackingmetrics.com/v1/ for API version 1.  
     * [TODO?] Authorization is handled via HMAC-SHA1 signing of each request and passing of the API key and signature in the authorization header.
     * To sign a request, first construct a UTF-8 multi-line string to sign containing the method, host, and query parameters.  For example, the a GET request to **http://recog.calltrackingmetrics.com/v1/orgs/{orgID}/reps?active=true** would be:
     * ```
     *     GET\n
     *     recog.calltrackingmetrics.com\n
     *     /v1/orgs/{orgID}/reps\n
     *     active=true
     * ```
     * where each line but the last is terminated with the newline character.  Sign the string above using HMAC-SHA1 with the secret key and then Base64 encode the string.  Pass the signed request in the Authorization headers as in:
     * ```
     *     Authorization: {APIKey}:{RequestSignature}
     * ```
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {GetAPIVersionAndTestAuthenticationResponse}
     */
    getAPIVersionAndTestAuthentication: function (callback) {

        //prepare query string for API call;
        var _baseUri = _configuration.BASEURI;
        
        var _queryBuilder = _baseUri + "/";
        
        //validate and preprocess url
        var _queryUrl = _APIHelper.cleanUrl(_queryBuilder);
        
        //prepare headers
        var _headers = {
            "accept": "application/json"
        };

        //Construct the request
        var _options = {
            queryUrl: _queryUrl,
            method: "GET",
            headers: _headers,
        };
        
        //Build the response processing. 
        function cb (_error, _response, _context) {
            if(_error) {
                callback({errorMessage: _error.message, errorCode: _error.code},null,_context);
            } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                var parsed = JSON.parse(_response.body);
                parsed = new GetAPIVersionAndTestAuthenticationResponse(parsed);
                callback(null,parsed,_context);
            } else {
                callback({errorMessage: "HTTP Response Not OK", errorCode: _response.statusCode, errorResponse: _response.body}, null, _context);
            }
        }
        _request(_options, cb);
    }

};

module.exports = AuthorizationController;