/*
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var assert = require('chai').assert;
var TestHelper = require('../TestHelper');
var APIHelper = require('../../lib/APIHelper');
var testerlib = require('../../lib');
var testConfiguration = require('../TestBootstrap');

var controller = testerlib.ClientsController;
 
var Retrieve a List of All Clients Response = testerlib.Retrieve a List of All Clients Response;
var Get a Client Response = testerlib.Get a Client Response;
var Update a Client Response = testerlib.Update a Client Response;
var Update a Client request = testerlib.Update a Client request;

describe('ClientsController Tests', function() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Client records are created automatically by the algorithm when an unknown voice is identified.  Client details can be updated via PUT (such as assigning a particular name to a caller.)  Clients have the following attributes:
* **id**
* **name**
* **created_at**
* **gender**
     */ 
    it('should testRetrieveAListOfAllClients1 response', function(done) {
        // Parameters for the API call
        var orgID = "null";

        controller.retrieveAListOfAllClients(orgID, function(error, response, context) {
            // Test response code
            assert.equal(200, context.response.statusCode);
            // Test headers
            var headers = [];
            headers["Content-Type"] = null ;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.equal("[    { \"id\": \"550e8400-e29b-41d4-a716-446324440000\", \"name\": \"Joe Client\", \"created_at\": \"2013-10-30T19:20:30-05:00\", \"gender\": \"male\"},    { \"id\": \"123d6754-e21b-32a3-a511-443224402100\", \"name\": \"Jane Client\", \"created_at\": \"2013-10-30T19:20:30-05:00\", \"gender\": \"female\"}            ]", context.response.body);
            done();
        });
    });

});
