/*
 * SpeakerRecognitionAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var assert = require('chai').assert;
var TestHelper = require('../TestHelper');
var APIHelper = require('../../lib/APIHelper');
var testerlib = require('../../lib');
var testConfiguration = require('../TestBootstrap');

var controller = testerlib.RepresentativesController;
 
var Retrieve a List of All Representatives Response = testerlib.Retrieve a List of All Representatives Response;
var Get a Representative Response = testerlib.Get a Representative Response;
var Create a Representative Response = testerlib.Create a Representative Response;
var Create a Representative request = testerlib.Create a Representative request;

describe('RepresentativesController Tests', function() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Representatives have the following attributes:
* **id**
* **name**
* **created_at**
* **gender**
* **active**
     */ 
    it('should testRetrieveAListOfAllRepresentatives1 response', function(done) {
        // Parameters for the API call
        var active = true;
        var orgID = "null";

        controller.retrieveAListOfAllRepresentatives(active, orgID, function(error, response, context) {
            // Test response code
            assert.equal(200, context.response.statusCode);
            // Test headers
            var headers = [];
            headers["Content-Type"] = null ;
            assert.isTrue(TestHelper.areHeadersProperSubsetOf(headers, context.response.headers, true));
            assert.isNotNull(response);
            assert.equal("[    { \"id\": \"550e8400-e29b-41d4-a716-446324440000\", \"name\": \"Joe Representative\", \"created_at\": \"2013-10-30T19:20:30-05:00\", \"gender\": \"male\", \"active\": true},    { \"id\": \"123d6754-e21b-32a3-a511-443224402100\", \"name\": \"Jane Representative\", \"created_at\": \"2013-10-30T19:20:30-05:00\", \"gender\": \"female\", \"active\": true}            ]", context.response.body);
            done();
        });
    });

});
